#!/bin/bash

# Squid Proxy Kurulumu Scripti

# Renkler
GREEN='\033[0;32m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# Hata Kontrolü
function check_error {
  if [ $? -ne 0 ]; then
    echo -e "${RED}Hata: $1${NC}"
    exit 1
  fi
}

# Script'in birden fazla kez çalıştırılmasını engelleme
if [ -f /tmp/script_already_run ]; then
  echo -e "${RED}Bu script daha önce çalıştırıldı.${NC}"
  exit 1
fi

touch /tmp/script_already_run

# 1. Script'i GitHub'dan İndirme
echo -e "${GREEN}1. Kurulum scripti GitHub'dan indiriliyor...${NC}"
wget -O setup_script.sh https://raw.githubusercontent.com/voltYazilim/otomatik_ipv4_proxy_olusturucu/refs/heads/main/index
check_error "Script GitHub'dan indirilemedi."

# 2. İndirilen Script'i Çalıştırma
echo -e "${GREEN}2. Script çalıştırılıyor...${NC}"

# Kendini çağırma döngüsünü engellemek için kontrol
if [ "$(basename "$0")" == "setup_script.sh" ]; then
  echo -e "${RED}setup_script.sh kendini çağırıyor, işlem durduruldu.${NC}"
  exit 1
fi

chmod +x setup_script.sh
./setup_script.sh
check_error "Kurulum scripti çalıştırılırken bir sorun oluştu."

# Kurulum Tamamlandı
echo -e "${GREEN}Kurulum tamamlandı! Sunucunuz şimdi HTTPS Proxy olarak çalışıyor.${NC}"
